// <auto-generated />

using GMWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMWeb.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20251216063940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GMWeb.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Award")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("award");

                    b.Property<int>("CreateTime")
                        .HasColumnType("int")
                        .HasColumnName("create_time");

                    b.Property<int>("DrowTime")
                        .HasColumnType("int")
                        .HasColumnName("drow_time");

                    b.Property<int>("Extra")
                        .HasColumnType("int")
                        .HasColumnName("extra");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pwd");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("salt");

                    b.Property<int>("SysId")
                        .HasColumnType("int")
                        .HasColumnName("sys_id");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uname");

                    b.HasKey("Uid");

                    b.ToTable("user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
